image:
  repository: ghcr.io/onedr0p/tautulli
  tag: 2.13.1


ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: tautulli-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100
