controllers:
  main:
    annotations:
      reloader.staketer.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 501
        fsGroup: 501
        runAsGroup: 501
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        image:
          repository: ghcr.io/rishikanthc/qbittorrent-vue
          tag: q4.6.2-v2.4.0

        securityContext:
          runAsUser: 501
          runAsGroup: 501

      gluetun:
        dependsOn: main
        image:
          repository: qmcgaw/gluetun
          tag: v3.37

        env:
          VPN_TYPE: wireguard
          VPN_INTERFACE: wg0

        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
              - NET_ADMIN

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true

persistence:
  config:
    enabled: true
    mountPath: /config

  # gluetun-data:
  #   type: emptyDir
  #   advancedMounts:
  #     main:
  #       gluetun:
  #         - path: /tmp/gluetun
  #       port-forward:
  #         - path: /tmp/gluetun
  #           readOnly: true
