mariadb:
  nameOverride: seafile-db
  fullnameOverride: seafile-db

  auth:
    existingSecret: seafile-db-auth

  primary:
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    persistence:
      enabled: true
      size: 8Gi

  secondary:
    replicaCount: 1
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    persistence:
      enabled: true
      size: 8Gi
