apiVersion: v2
name: authelia-ha
description: A Helm chart for deploying HA Authelia
type: application
sources:
  - https://github.com/authelia/authelia
  - http://authelia.com/

version: 0.1.0
appVersion: "1.16.0"
kubeVersion: ">=1.22.0-0"

keywords:
  - authelia
  - authentication
  - authorization
  - sso

dependencies:
  - name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.2
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.0
  - name: authelia
    repository: https://charts.authelia.com
    version: 0.8.57
