authelia:
  domain: "example.com"

  ingress:
    enabled: true
    certManager: false
    subdomain: auth

    tls:
      enabled: false
      secret: authelia-tls

    traefikCRD:
      enabled: false
      entryPoints:
        - websecure
      sticky: true

  pod:
    env:
      - name: TZ
        value: "USA/Los_Angeles"

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  configMap:
    enabled: true

    log:
      level: debug

    session:
      redis:
        enabled: true
        enabledSecret: true
        maximumActiveConnections: 8
        minimumIdleConnections: 2
        host: session-db.default.svc.cluster.local
        port: 26379

        high_availability:
          enabled: true
          enabledSecret: true
          sentinel_name: redis-master

    storage:
      local:
        enabled: false
      mysql:
        enabled: false
      postgres:
        enabled: true
        host: storage-db-postgresql.default.svc.cluster.local
        port: 5432
        database: authelia
        username: authelia

  certificates:
    existingSecret: authelia-tls

  secret:
    existingSecret: authelia-app
    jwt:
      key: jwt
    ldap:
      key: ldap-password
    storage:
      key: storage-password
    storageEncryptionKey:
      key: storageEncryptionKey
    session:
      key: session
    redis:
      key: redis-password
    redisSentinel:
      key: redis-password
    smtp:
      key: smtp
    # oidcPrivateKey:
    #   key: oidcPrivateKey
    # oidcHMACSecret:
    #   key: oidcHMACSecret

postgresql-ha:
  nameOverride: storage-db
  fullnameOverride: storage-db

  global:
    storageClass: "local-path"

  postgresql:
    username: authelia
    database: authelia
    existingSecret: authelia-storage

    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"

  persistence:
    enabled: true
    size: 1Gi

redis:
  nameOverride: session-db
  fullnameOverride: session-db

  global:
    storageClass: "local-path"

  auth:
    existingSecret: authelia-session
    existingSecretPasswordKey: redis-password

  master:
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  replica:
    persistence:
      size: 1Gi
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  sentinel:
    enabled: true
    masterSet: redis-master
    resources:
      requests:
        cpu: "600m"
        memory: "768Mi"
      limits:
        cpu: 1
        memory: "1Gi"
