controllers:
  main:
    annotations:
      reloader.staketer.com/auto: "true"

    containers:
      main:
        image:
          repository: bellamy/wallos
          tag: 1.5.0
        env:
          TZ: "America/Los_Angeles"

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 80

persistence:
  db:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: false
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        db:
          - path: /var/www/html/db

  logos:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: false
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        logos:
          - path: /var/www/html/images/uploads/logos
