controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        hostname: netb
        image:
          repository: netbirdio/netbird
          tag: 0.25.4

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE

        env:
          NB_SETUP_KEY: 8A8A90B3-981C-4D3D-B4AC-E25CC93FEC84

      daashboard:
        image:
          repository: wiretrustee/dashboard
          tag: main

        env:
          AUTH0_DOMAIN: dev-e8ee77vb4qjit4oj.us.auth0.com
          AUTH0_CLIENT_ID: naj64sWR1RFvgU0IjUnLkxYsLke42VcF
          AUTH0_AUDIENCE: https://nb.rkth.io
          NETBIRD_MGMT_API_ENDPOINT: http://localhost:33073
          NGINX_SSL_PORT: 443
          LETSENCRYPT_DOMAIN: nb.rkth.io
          LETSENCRYPT_EMAIL: rcnoetic@gmail.com

service:
  main:
    type: ClusterIP
    ports:
      http:
        primary: false
        port: 80
      https:
        port: 443
  mgmt:
    controller: main
    type: ClusterIP
    ports:
      http:
        primary: true
        enabled: true
        port: 33073

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "acme-issuer"
      # gethomepage.dev/enabled: "true"
      # gethomepage.dev/name: "Redlib"
      # gethomepage.dev/description: "Reddit frontend"
      # gethomepage.dev/group: "Social"
      # gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/libreddit.png"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: auth-secured@kubernetescrd
    hosts:
      - host: "nb.rkth.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
    tls:
      - hosts:
          - "nb.rkth.io"
        secretName: redlib-tls
  mgmt:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "acme-issuer"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "mnb.rkth.io"
        paths:
          - path: /
            pathType: Prefix
            service:
              name: mgmt
    tls:
      - hosts:
          - "mnb.rkth.io"
        secretName: mgmt-tls

persistence:
  client:
    enabled: true
    mountPath: /client
    storageClass: longhorn
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /etc/netbird
