image:
  repository: ghcr.io/onedr0p/prowlarr
  tag: 1.7.4.3769

controller:
  type: statefulset
  strategy: RollingUpdate

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: prr.rkth.io
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: prowlarr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 24Mi
    retain: true
    mountPath: /config

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

env:
  TZ: America/Los_Angeles
  PROWLARR__URL_BASE: https://prr.rkth.io
  PROWLARR__LOG_LEVEL: debug
  PROWLARR__POSTGRES_MAIN_DB: prowlarr
  PROWLARR__POSTGRES_LOG_DB: prowlarr_log
  PROWLARR__POSTGRES_HOST: prowlarr-db.appspace.svc.cluster.local
  PROWLARR__POSTGRES_USER:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: username
  PROWLARR__POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: user-password

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    memory: 512Mi
    cpu: 100m

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /ping
        port: 9696
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /ping
        port: 9696
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: false

postgresql:
  nameOverride: prowlarr-db
  fullnameOverride: prowlarr-db
  global:
    storageClass: longhorn

    postgresql:
      auth:
        username: prowlarr
        database: prowlarr
        existingSecret: prowlarr-secret

        secretKeys:
          adminPasswordKey: admin-password
          userPasswordKey: user-password
          replicationPasswordKey: replication-password
  primary:
    persistence:
      storageClass: longhorn
      size: 1Gi
