image:
  repository: ghcr.io/onedr0p/prowlarr
  tag: 1.7.4.3769

controller:
  type: statefulset
  strategy: RollingUpdate

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: prr.rkth.io
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: prowlarr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    type: nfs
    server: 207.246.100.141
    path: /mnt/blockstorage/skidobo/media-stack/configs/prowlarr
    retain: true
    mountPath: /config

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

env:
  TZ: America/Los_Angeles
  PROWLARR__URL_BASE: https://prr.rkth.io
  PROWLARR__LOG_LEVEL: debug
  PROWLARR__POSTGRES_MAIN_DB: prowlarr
  PROWLARR__POSTGRES_LOG_DB: prowlarr_log
  PROWLARR__POSTGRES_HOST: prowlarr-db.appspace.svc.cluster.local
  PROWLARR__POSTGRES_USER:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: username
  PROWLARR__POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: user-password

resources:
  requests:
    cpu: 0.5
    memory: 512Mi
  limits:
    memory: 1Gi
    cpu: 1

initContainers:
  init-db:
    image: ghcr.io/onedr0p/postgres-init:14.9
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: prowlarr-init-secret


postgresql:
  nameOverride: prowlarr-db
  fullnameOverride: prowlarr-db
  global:
    storageClass: longhorn

    postgresql:
      auth:
        username: prowlarr
        database: prowlarr
        existingSecret: prowlarr-secret

        secretKeys:
          adminPasswordKey: admin-password
          userPasswordKey: user-password
          replicationPasswordKey: replication-password
  primary:
    persistence:
      storageClass: longhorn
      size: 512Mi
