image:
  repository: ghcr.io/onedr0p/prowlarr-develop
  tag: 1.10.1.4059

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: prowlarr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 9696
        targetPort: 9696

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config

# podSecurityContext:
#   runAsUser: 568
#   fsGroup: 568
#   runAsGroup: 568
#   fsGroupChangePolicy: "OnRootMismatch"
#   supplementalGroups:
#     - 100

env:
  TZ: America/Los_Angeles
  PROWLARR__URL_BASE: ""
  PROWLARR__LOG_LEVEL: debug
  PROWLARR__POSTGRES_MAIN_DB: prowlarr
  PROWLARR__POSTGRES_LOG_DB: prowlarr_log
  PROWLARR__POSTGRES_HOST: prowlarr-db.default.svc.cluster.local
  PROWLARR__POSTGRES_USER:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: username
  PROWLARR__POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: prowlarr-secret
        key: user-password

initContainers:
  init-db:
    image: ghcr.io/onedr0p/postgres-init:14.9
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: prowlarr-init-secret

postgresql:
  enabled: false
  nameOverride: prowlarr-db
  fullnameOverride: prowlarr-db
  auth:
    username: prowlarr
    database: prowlarr
    existingSecret: prowlarr-secret

    secretKeys:
      adminPasswordKey: admin-password
      userPasswordKey: user-password
      replicationPasswordKey: replication-password
  primary:
    persistence:
      storageClass: longhorn-custom

postgresql-ha:
  enabled: false
#   nameOverride: prowlarr-db
#   fullnameOverride: prowlarr-db

#   global:
#     storageClass: "local-path"

#   postgresql:
#     username: postgres
#     # database: prowlarr
#     existingSecret: prowlarr-secret

#   persistence:
#     enabled: true
#     size: 3Gi
