controllers:
  main:
    enabled: true
    type: deployment

    pod:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    containers:
      main:
        image:
          repository: daya0576/beaverhabits
          tag: 0.4.4
          pullPolicy: Always
        env:
          HABITS_STORAGE: USER_DISK
          MAX_USER_COUNT: 1
          ENABLE_IOS_STANDALONE: true
          TRUSTED_LOCAL_EMAIL: dray@tuta.com

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 8080

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8080
    tls:
      - secretName: beaver-tls

persistence:
  config:
    enabled: true
    storageClass: longhorn
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
    globalMounts:
      - path: /app/.user/
        readOnly: false
