apiVersion: v2
name: audiobookshelf
description: A Helm chart for audiobookshelf

type: application
version: 0.1.0

appVersion: "2.11"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
