defaultPodOptions:
  labels:
    app: audiobookshelf

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/advplyr/audiobookshelf
          # -- image tag
          tag: 2.11
service:
  main:
    enabled: true
    ports:
      http:
        port: 80
        targetPort: 80

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
    tls:
      - secretName: audiobookshelf-tls

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config
  # audiobooks:
  #   enabled: true
  #   mountPath: /audiobooks
  #   accessMode: ReadWriteOnce
  # podcasts:
  #   enabled: true
  #   mountPath: /podcasts
  #   accessMode: ReadWriteOnce
  metadata:
    enabled: true
    mountPath: /metadata
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
