controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        #   image:
        #     repository: nvidia/cuda
        #     tag: 12.3.1-runtime-ubuntu22.04
        #   securityContext:
        #     runAsUser: 1000
        #     runAsGroup: 1000
        #   resources:
        #     requests:
        #       nvidia.com/gpu: 1
        #     limits:
        #       nvidia.com/gpu: 1
        #   command:
        #     - "/bin/sh"
        #     - "-c"
        #     - "while true; do sleep 3600; done"
        # syncthing:
        image:
          repository: syncthing/syncthing
          tag: 1.27.3
        resources:
          requests:
            cpu: 15m
            memory: 100M
          limits:
            cpu: 100m
            memory: 200M

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8080
  ssh:
    type: ClusterIP
    controller: main
    ports:
      ssh:
        port: 22
  syncui:
    controller: main
    # selector:
    #   app: syncthing
    ports:
      syncui:
        port: 8384
  listen:
    controller: main
    # externalTrafficPolicy: Local
    # ipFamilyPolicy: PreferDualStack
    ports:
      listen:
        port: 22000
  discovery:
    controller: main
    ports:
      discovery:
        port: 21027
        protocol: UDP

persistence:
  cookiejar:
    enabled: true
    type: hostPath
    hostPath: /home/rishi/cookiejar
    accessMode: ReadWriteMany
    retain: true
