controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        image:
          repository: nvidia/cuda
          tag: 12.3.1-runtime-ubuntu22.04
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8080
  ssh:
    type: ClusterIP
    ports:
      ssh:
        port: 22

ingress:
  main:
    enabled: true
    controller: main
  ssh:
    enabled: true
    controller: main

persistence:
  cookiejar:
    enabled: true
    type: hostPath
    hostPath:
      path: /home/rishi/cookiejar
    accessMode: ReadWriteMany
    retain: true
