controllers:
  main:
    containers:
      # main:
      #   image:
      #     repository: syncthing/syncthing
      #     tag: 1.27.3
      #   resources:
      #     requests:
      #       cpu: 15m
      #       memory: 64M
      #     limits:
      #       cpu: 100m
      #       memory: 128M
      main:
        image:
          repository: ghcr.io/rishikanthc/cuda-ssh
          tag: 12.3.1-runtime-ubuntu22.04
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        command:
          - "/bin/bash"
          - "-c"
          - "while true; do sleep 30; done;"
        probes:
          readiness:
            custom: true
            exec:
              command:
                - nvidia-smi
          startup:
            enabled: false
            custom: true
            exec:
              command:
                - nvidia-smi
service:
  # main:
  #   ports:
  #     http:
  #       port: 8384
  # listen:
  #   enabled: true
  #   type: LoadBalancer
  #   controller: main
  #   ports:
  #     discovery:
  #       enabled: true
  #       port: 21027
  #       protocol: UDP
  #     listen:
  #       enabled: true
  #       port: 22000
  #       protocol: TCP
  #     listen-udp:
  #       enabled: true
  #       port: 22000
  #       protocol: UDP
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        port: 9000
      ssh:
        enabled: true
        port: 22
        targetPort: 22

persistence:
  cookiejar:
    enabled: true
    type: hostPath
    hostPath: /home/rishi/cookiejar
    accessMode: ReadWriteMany
    retain: true
