controller:
  type: statefulset
image:
  repository: docker.io/plexinc/pms-docker
  tag: 1.32.5.7516-8f4248874

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: plex-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config
  transcode:
    enabled: true
    type: emptyDir
  media:
    enabled: true
    retain: true
    mountPath: /data

env:
  TZ: America/Los_Angeles

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsGroup: 1000
  # fsGroupChangePolicy: "OnRootMismatch"
  # supplementalGroups:
  #   - 27
  #   - 100
