image:
  repository: linuxserver/plex
  tag: 1.32.5.7516-8f4248874

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: plex-tls

service:
  main:
    ports:
      http:
        port: 32400
        protocol: TCP
      dlna-tcp:
        port: 32469
        protocol: TCP
        enabled: true
      dlna-udp:
        port: 1900
        protocol: UDP
        enabled: true
      plex-companion:
        port: 3005
        protocol: TCP
        enabled: true
      discovery-udp:
        port: 5353
        protocol: UDP
        enabled: true
      plex-roku:
        port: 8324
        protocol: TCP
        enabled: true
      gdm-32410:
        port: 32410
        protocol: UDP
        enabled: true
      gdm-32412:
        port: 32412
        protocol: UDP
        enabled: true
      gdm-32413:
        port: 32413
        protocol: UDP
        enabled: true
      gdm-32414:
        port: 32414
        protocol: UDP
        enabled: true

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config
  transcode:
    enabled: true
    type: emptyDir
  media:
    enabled: true
    retain: true
    mountPath: /data

env:
  TZ: America/Los_Angeles

podSecurityContext:
  runAsUser: 107
  fsGroup: 111
  runAsGroup: 111
  # fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 1000
