global:
  nameOverride: filebrowser
  fullnameOverride: filebrowser

controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: filebrowser/filebrowser
          tag: v2
          pullPolicy: Always
        args:
          - "--database=/db/database.db"
          - "--root=/srv"

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 80
        targetPort: 80

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 80
    tls:
      - secretName: filebrowser-tls

persistence:
  db:
    enabled: true
    storageClass: longhorn
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
  srv:
    enabled: true
    type: nfs
    server: 10.0.0.243
    path: /nfs/rms/
