image:
  repository: ghcr.io/onedr0p/sabnzbd
  tag: 4.0.3

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8080
        targetPort: 8080


ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: sabnzbd-tls

env:
  TZ: America/Los_Angeles
  DOCKER_MODS: ghcr.io/gilbn/theme.park:sabnzbd

  SABNZBD__HOST_WHITELIST_ENTRIES: >-
    sabnzbd,
    sabnzbd.appsapce,
    sabnzbd.appsapce.svc,
    sabnzbd.appsapce.svc.cluster,
    sabnzbd.appsapce.svc.cluster.local,
    nzbd.rkth.io

envFrom:
  - secretRef:
      name: sabnzbd-secret

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

securityContext:
  privileged: true

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 24Mi
    retain: true
  media:
    enabled: true
    type: nfs
    server: 207.246.100.141
    path: /mnt/blockstorage/skidobo/media-stack
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true
  # media:
  #   enabled: true
  #   type: nfs
  #   server: 207.246.100.141
  #   path: /mnt/blockstorage/skidobo/media-stack
  #   mountPath: /media
  #   retain: true

resources:
  requests:
    cpu: 300m
    memory: 1Gi
  limits:
    memory: 2Gi
