image:
  repository: ghcr.io/onedr0p/sabnzbd
  tag: 4.2.3

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8080
        targetPort: 8080

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: sabnzbd-tls

env:
  TZ: America/Los_Angeles

  # add hostname as well as all possible subdomains to the whitelist
  # change 'default' to the namespace where sabnzbd is deployed
  SABNZBD__HOST_WHITELIST_ENTRIES: >-
    sabnzbd,
    sabnzbd.default,
    sabnzbd.default.svc,
    sabnzbd.default.svc.cluster,
    sabnzbd.default.svc.cluster.local

envFrom:
  - secretRef:
      name: sabnzbd-secret

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

securityContext:
  privileged: true

persistence:
  config:
    enabled: true
    mountPath: /config
    retain: true
  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true

# resources:
#   requests:
#     cpu: 100m
#     memory: 256Mi
#   limits:
#     cpu: 500m
#     memory: 512Mi

addons:
  vpn:
    enabled: false
    type: gluetun

    gluetun:
      image:
        repository: docker.io/qmcgaw/gluetun
        tag: v3.35.0

    env:
      TZ: America/Los_Angeles

    securityContext:
      runAsUser: 0
      runAsGroup: 0

    scripts:
      up: |-
        !/bin/sh
        echo "connected" > /shared/vpnstatus

      down: |-
        !/bin/sh
        echo "disconnected" > /shared/vpnstatus
