image:
  repository: ghcr.io/miniflux/miniflux
  pullPolicy: IfNotPresent
  tag: 2.0.47

controller:
  strategy: RollingUpdate

env:
  baseURL:
    secretKeyRef:
      name: miniflux
      key: baseURL

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: miniflux-tls
        hosts:
          - ""

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8080
        targetPort: 8080
