# controller:
#   type: statefulset
#   replicas: 2
image:
  repository: ghcr.io/miniflux/miniflux
  pullPolicy: IfNotPresent
  tag: 2.0.49-distroless

env:
  RUN_MIGRATIONS: 1
  # BASE_URL:
  #   secretKeyRef:
  #     name: miniflux
  #     key: baseUrl
  DATABASE_URL:
    secretKeyRef:
      name: miniflux
      key: dbUrl

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: miniflux-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8080
        targetPort: 8080

resources:
  requests:
    cpu: 0.25
    memory: 128Mi
  limits:
    cpu: 0.5
    memory: 256Mi

## Postgres config
postgresql-ha:
  enabled: false
  nameOverride: miniflux-db
  fullnameOverride: miniflux-db

  global:
    storageClass: "local-path"

  postgresql:
    username: miniflux
    database: miniflux
    existingSecret: miniflux-db-secret

  persistence:
    enabled: true
    size: 3Gi

postgresql:
  enabled: false
  nameOverride: miniflux-db
  fullnameOverride: miniflux-db

  global:
    storageClass: "local-path"

    postgresql:
      auth:
        username: miniflux
        database: miniflux
        existingSecret: miniflux-db-secret

        secretKeys:
          adminPasswordKey: admin-password
          userPasswordKey: user-password
          replicationPasswordKey: replication-password
    auth:
      username: miniflux
      database: miniflux
      existingSecret: miniflux-db-secret

      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
