image:
  repository: ghcr.io/miniflux/miniflux
  pullPolicy: IfNotPresent
  tag: 2.0.47

controller:
  strategy: RollingUpdate

env:
  BASE_URL:
    secretKeyRef:
      name: miniflux
      key: baseUrl
  DATABASE_URL:
    secretKeyRef:
      name: miniflux
      key: dbUrl

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: miniflux-tls
        hosts:
          - ""

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8080
        targetPort: 8080


## Postgres config

postgresql:
  nameOverride: miniflux-db
  fullnameOverride: miniflux-db

  global:
    storageClass: longhorn

    postgresql:
      auth:
        username: miniflux
        database: miniflux
        existingSecret: miniflux-db-secret

        secretKeys:
          adminPasswordKey: admin-password
          userPasswordKey: user-password
          replicationPasswordKey: replication-password
    auth:
      username: miniflux
      database: miniflux
      existingSecret: miniflux-db-secret

      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
