image:
  repository: lscr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: v23.08.2-ls103

controller:
  strategy: RollingUpdate

env:
  APP_URL: ""
  DB_HOST: bookstack-db.default.svc.cluster.local
  DB_PORT: 3306
  DB_DATABASE: bookstack
  DB_USERNAME: bookstack
  DB_PASSWORD:
    secretKeyRef:
      name: bookstack-db-secret
      key: mariadb-password

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: bookstack-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 80
        targetPort: 80

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    memory: 4Gi

mariadb:
  enabled: true
  nameOverride: bookstack-db
  fullnameOverride: bookstack-db

  auth:
    database: bookstack
    username: bookstack
    existingSecret: bookstack-db-secret

  primary:
    persistence:
      size: 1Gi

mariadb-galera:
  enabled: false
  nameOverride: bookstack-db
  fullnameOverride: bookstack-db

  existingSecret: bookstack-db-secret

  db:
    user: bookstack
    name: bookstack

  galera:
    bootstrap:
      bootstrapFromNode: 0

  persistence:
    size: 1Gi

redis:
  enabled: false
  nameOverride: bookstack-sessions-db
  fullnameOverride: bookstack-sessions-db
  auth:
    existingSecret: bookstack-session-secret
    existingSecretPasswordKey: password

  master:
    persistence:
      size: 1Gi

  replica:
    persistence:
      size: 1Gi

  sentinel:
    enabled: true
    masterSet: redis-master
