global:
  labels:
    app: emby

controllers:
  main:
    containers:
      main:
        image:
          repository: emby/embyserver
          tag: latest
          pullPolicy: Always

service:
  main:
    # type: ClusterIP
    ports:
      http:
        port: 8096
        targetPort: 8096
      https:
        enabled: true
        port: 8920
        targetPort: 8920

# ingress:
#   main:
#     enabled: true
#     className: traefik
#     hosts:
#       - host: ""
#         paths:
#           - path: /
#             pathType: Prefix
#             service:
#               name: main
#               port: http
#     tls:
#       - secretName: emby-tls

persistence:
  config:
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config
  transcode:
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /transcode

defaultPodOptions:
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
