apiVersion: v2
name: recyclarr
description: A Helm chart for recyclarr

type: application
version: 0.1.0
appVersion: "6.0.1"
kubeVersion: ">=1.22.0-0"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
