image:
  repository: ghcr.io/onedr0p/radarr
  tag: 4.7.5.7809

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: radarr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 7878
        targetPort: 7878

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

env:
  TZ: America/Los_Angeles
  RADARR__POSTGRES_MAIN_DB: radarr
  RADARR__POSTGRES_LOG_DB: radarr_log
  RADARR__POSTGRES_HOST: radarr-db.default.svc.cluster.local
  RADARR__POSTGRES_USER:
    valueFrom:
      secretKeyRef:
        name: radarr-secret
        key: username
  RADARR__POSTGRES_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: radarr-secret
        key: user-password



persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config
  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true

initContainers:
  init-db:
    image: ghcr.io/onedr0p/postgres-init:14.9
    imagePullPolicy: IfNotPresent
    envFrom:
      - secretRef:
          name: radarr-init-secret

postgresql:
  nameOverride: radarr-db
  fullnameOverride: radarr-db
  auth:
    username: radarr
    database: radarr
    existingSecret: radarr-secret

    secretKeys:
      adminPasswordKey: admin-password
      userPasswordKey: user-password
      replicationPasswordKey: replication-password
  primary:
    persistence:
      storageClass: longhorn-custom
