apiVersion: v2
name: paperless-ngx
description: A Helm chart for paperless ngx

type: application
version: 0.1.0
appVersion: "1.17.4"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.2
    condition: postgresql-ha.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.0.0
    condition: redis.enabled
