apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-prowlarr
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  template:
    spec:
      containers:
      - name: create-db-prowlarr
        image: bitnami/postgresql:latest
        command:
          - psql
          - '-h'
          - prowlarr-db.appspace.svc.cluster.local
          - '-U'
          - prowlarr
          - '-d'
          - prowlarr
          - '-c'
          - 'CREATE DATABASE prowlarr_log;'
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: prowlarr-secret
                key: user-password
      restartPolicy: OnFailure
