defaultPodOptions:
  labels:
    app: calibre

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/calibre-web
          tag: 0.6.21
    initContainers:
      init-calibre: # This is a unique identifier for the init container
        name: initcalibre
        image:
          repository: busybox
          tag: latest
        command:
          - "sh"
          - "-c"
          - "chown -R 1000:1000 /config && chmod -R 755 /config"
        volumeMounts:
          - name: config
            mountPath: /config

service:
  main:
    enabled: true
    ports:
      http:
        port: 8083
        targetPort: 8083

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
    tls:
      - secretName: calibre-tls

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
