defaultPodOptions:
  labels:
    app: calibre

controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/calibre-web
          tag: 0.6.21

service:
  main:
    enabled: true
    ports:
      http:
        port: 8083
        targetPort: 8083

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
    tls:
      - secretName: calibre-tls

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
