image:
  repository: ghcr.io/onedr0p/flood
  pullPolicy: IfNotPresent
  tag: 4.7.0

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: flood-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 3000
        targetPort: 3000

persistentVolumeClaim:
  enabled: true
  mountPath: /config

resources:
  requests:
    memory: 256Mi
  limits:
    cpu: 0.5
    memory: 512Mi
