apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin
type: application
version: 0.1.0

appVersion: "1.16.0"
kubeVersion: ">=1.22.0-0"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
