image:
  repository: ghcr.io/onedr0p/jellyfin
  tag: 10.8.10

controller:
  type: statefulset
  strategy: RollingUpdate

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: fin.rkth.io
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: jellyfin-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8096
        targetPort: 8096

env:
  TZ: America/Los_Angeles

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 24Mi
    retain: true
    mountPath: /config
  media:
    enabled: true
    type: nfs
    server: 207.246.100.141
    path: /mnt/blockstorage/skidobo/media-stack/media
    mountPath: /data/media
    retain: true
  transcode:
    enabled: true
    type: emptyDir
    medium: Memory
