image:
  repository: ghcr.io/onedr0p/jellyfin
  tag: 10.8.10

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: jellyfin-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 8096
        targetPort: 8096

env:
  TZ: America/Los_Angeles

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config
  media:
    enabled: true
    mountPath: /data/media
    retain: true
  transcode:
    enabled: true
    type: emptyDir
    medium: Memory

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100
