controllers:
  main:
    annotations:
      reloader.staketer.com/auto: "true"

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/jellyfin
          tag: 10.8

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8096

ingress:
  main:
    enabled: true

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 16Gi
