---
{{- if .Values.initdb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db-job
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ .Values.initdb.secretName }}
      restartPolicy: OnFailure
{{- end }}
