image:
  repository: ghcr.io/onedr0p/bazarr
  tag: 1.4.5

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: bazarr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 6767
        targetPort: 6767

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

env:
  TZ: America/Los_Angeles

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /config
  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    retain: true
