apiVersion: v2
name: lidarr
description: A Helm chart for Kubernetes
type: application
version: 0.1.2

appVersion: "2.1.3.3927"
kubeVersion: ">=1.22.0-0"

dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.11.1
