global:
  nameOverride: autobrr
  fullnameOverride: autobrr

controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: ghcr.io/autobrr/autobrr
          tag: latest
          pullPolicy: IfNotPresent
        env:
          TZ: 'America/Los_Angeles'
        

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 7474
        targetPort: 7474

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 7474
    tls:
      - secretName: autobrr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true


