controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: glanceapp/glance
          tag: v0.6.4
          pullPolicy: Always
        args:
          - --config
          - /config/glance.yaml
        env:
          TZ: "America/Los_Angeles"

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 8080

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8080
    tls:
      - secretName: glance-tls

configMaps:
  config:
    enabled: true
    data:
      glance.yaml: |
        pages:
          - name: Home
            columns:
              - size: small
                widgets:
                  - type: calendar
                  - type: bookmarks
                    groups:
                      - links:
                          - title: Noetic
                            url: https://mail.google.com/mail/u/0/
                          - title: Dray
                            url: https://app.tuta.com/mail/OHi6UUG-1o-9
                          - title: Google
                            url: https://google.com
                          - title: YouTube
                            url: https://www.youtube.com/
                      - title: work
                        color: 10 70 50
                        links:
                          - title: Hub
                            url: https://hub.corp.ebay.com/
                          - title: Notebooks
                            url: https://aip.vip.ebay.com/notebook/list
                      - title: social
                        color: 200 50 50
                        links:
                          - title: Whatsapp
                            url: https://web.whatsapp.com
                          - title: Reddit
                            url: https://reddit.com
                  - type: repository
                    repository: rishikanthc/Scriberr
                    pull-requests-limit: 3
                    issues-limit: 3
                  - type: repository
                    repository: rishikanthc/markopolis
                    pull-requests-limit: 3
                    issues-limit: 3
              - size: full
                widgets:
                  - type: hacker-news
                  - type: videos
                    channels:
                      - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                      - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                      - UCYO_jab_esuFRV4b17AJtAw # 3Blue1Brown
                      - UCXuqSBlHAE6Xw-yeJA0Tunw # LinusTechTips
                  - type: group
                    widgets:
                      - type: reddit
                        subreddit: selfhosted
                      - type: reddit
                        subreddit: technology
                      - type: reddit
                        subreddit: news
              - size: small
                widgets:
                  - type: weather
                    location: Bellevue, Washington, United States
                  - type: clock
                    hour-format: 24h
                    timezones:
                      - timezone: America/Los_Angeles
                        label: Bellevue
                      - timezone: Asia/Kolkata
                        label: India
                      - timezone: America/Chicago
                        label: Austin / Chicago
                      - timezone: America/New_York
                        label: New York

persistence:
  config:
    enabled: true
    type: configMap
    name: glance-config
    identifier: config
    advancedMounts:
      main:
        main:
          - path: /config/glance.yaml
            subPath: glance.yaml
            readOnly: false
            
