controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: glanceapp/glance
          tag: v0.6.4
          pullPolicy: Always
        args:
          - --config
          - /config/glance.yaml
        env:
          TZ: "America/Los_Angeles"

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 8080

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 8080
    tls:
      - secretName: glance-tls

configMaps:
  config:
    enabled: true
    data:
      glance.yaml: |
        pages:
          - name: Home
            columns:
              - size: small
                widgets:
                  - type: calendar
                  - type: bookmarks
                    groups:
                      - links:
                          - title: Noetic
                            url: https://mail.google.com/mail/u/0/
                          - title: Dray
                            url: https://app.tuta.com/mail/OHi6UUG-1o-9
                          - title: Google
                            url: https://google.com
                      - work:
                          - title: Hub
                            url: https://hub.corp.ebay.com/
                          - title: Notebooks
                            url: https://aip.vip.ebay.com/notebook/list
                      - social:
                          - title: Whatsapp
                            url: https://web.whatsapp.com
                          - title: Reddit
                            url: https://reddit.com
                  - type: rss
                    limit: 10
                    collapse-after: 3
                    cache: 3h
                    feeds:
                      - url: https://ciechanow.ski/atom.xml
                      - url: https://www.joshwcomeau.com/rss.xml
                        title: Josh Comeau
                      - url: https://samwho.dev/rss.xml
                      - url: https://awesomekling.github.io/feed.xml
                      - url: https://ishadeed.com/feed.xml
                        title: Ahmad Shadeed
              - size: full
                widgets:
                  - type: hacker-news
                  - type: videos
                    channels:
                      - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                      - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - type: reddit
                    subreddit: selfhosted
              - size: small
                widgets:
                  - type: weather
                    location: USA, Bellevue
                  - type: clock
                    hour-format: 24h
                    timezones:
                      - timezone: America/Los_Angeles
                        label: Bellevue
                      - timezone: Asia/Kolkata
                        label: India
                      - timezone: America/Chicago
                        label: Austin / Chicago
                      - timezone: America/New_York
                        label: New York

persistence:
  config:
    enabled: true
    type: configMap
    name: glance-config
    identifier: config
    advancedMounts:
      main:
        main:
          - path: /config/glance.yaml
            subPath: glance.yaml
            readOnly: false
            
