controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: stonith404/pocket-id
          tag: v0.27
          pullPolicy: Always
        env:
          PUBLIC_APP_URL: https://pid.rkth.io
          TRUST_PROXY: true
          SQLITE_DB_PATH: /data/pocket-id.db

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 80

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 80
    tls:
      - secretName: pocketid-tls

persistence:
  data:
    enabled: true
    storageClass: longhorn
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
