controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: stonith404/pocket-id
          tag: v1.1.0
          pullPolicy: Always
        env:
          APP_URL: https://pid.rkth.io
          TRUST_PROXY: true
          MAXMIND_LICENSE_KEY:
            valueFrom:
              secretKeyRef:
                name: pocketid-secret
                key: license

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        port: 80

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 1411
    tls:
      - secretName: pocketid-tls

persistence:
  data:
    enabled: true
    storageClass: longhorn
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    globalMounts:
      - path: /app/backend/data
        readOnly: false
