global:
  nameOverride: wizarr
  fullnameOverride: wizarr

controllers:
  main:
    enabled: true
    type: deployment

    containers:
      main:
        image:
          repository: ghcr.io/wizarrrr/wizarr
          tag: 4.2.0-beta.3
          pullPolicy: IfNotPresent
        

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 5690
        targetPort: 5690

ingress:
  main:
    enabled: false
    className: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 5690
    tls:
      - secretName: wizarr-tls

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    mountPath: /data/database
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    globalMounts:
      - path: /data/database
        readOnly: false


