image:
  repository: docker.io/fallenbagel/jellyseerr
  tag: 1.6.0

ingress:
  main:
    enabled: false
    ingressClassName: traefik
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: jellyseerr-tls

service:
  main:
    ports:
      http:
        protocol: TCP
        port: 5055
        targetPort: 5055

podSecurityContext:
  runAsUser: 568
  fsGroup: 568
  runAsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 100

env:
  TZ: America/Los_Angeles

persistence:
  config:
    enabled: true
    retain: true
    mountPath: /app/config

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 2Gi
